# Generated by Django 5.1.3 on 2025-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_event_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='qr_code_data',
            field=models.TextField(null=True),
        ),
    ]
